default_platform(:ios)

platform :ios do
  desc "login"
  app_store_connect_api_key(
    key_id: "XFQ94S4AWH",
    issuer_id: "c481f9bd-73fa-46d4-a81e-55ae31ef6a1c",
    key_filepath: "./fastlane/AuthKey_XFQ94S4AWH.p8",
    in_house: false
  )
 
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "githubActionsTest",
      export_method: "app-store",
      export_options: {
      signingStyle: "manual",
        provisioningProfiles: {
          "com.smart.mind.task.githubActionsTest" => "appstoreload"
        }
      }
   )
    upload_to_testflight
  end
end


