default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"],
      in_house: false
    )

  build_app(
      scheme: "githubActionsTest",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      },
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight
  end
end
