name: Build React Native Android APK

on:
  workflow_dispatch:
    branches: [ release_2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
#       1. Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Show directory tree
        run: ls -R android/app

      # 2. Set up Java (React Native uses Java 11+)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.11'

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.11.0'

      # 4. Install dependencies
      - name: Install dependencies
        run: yarn
        continue-on-error: true

      # 5. Install Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3


      # 6. Grant Gradle permission
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 7. Build the APK
      - name: Build debug APK
        run: yarn apk:dev

      # 8. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: react-native-apk
          path: android/app/build/outputs//apk/development/debug/app-development-debug.apk
